import {
  CookieQuestFeatImg,
  DrivenAdFeatImg,
  DrivenAdImg01,
  DrivenAdImg02,
  DrivenAdImg03,
  DrivenAdImg04,
  ElectricRaceCarFeatImg,
  HMTHSAutoCad3dFeatImg,
  HMTHSCampus3dFeatImg,
  HMTHSClassroom3dFeatImg,
  HMTHSStemLab3dFeatImg,
  LogoBackdrop,
  MoondripFeatImg,
  MountainDewAdFeatImg,
  NecroImg01,
  NecroImg02,
  NecroImg03,
  NecroImg04,
  OfficeSpaceFeatImg,
  OfficeSpaceImg01,
  OfficeSpaceImg02,
  SolarAprtFeatImg,
  TheVaultFeatImg,
} from "@/assets";

export const projects = [
  {
    id: 1,
    title: `Necro's Revenge`,
    summary: `2D top-down hack-and-slash RPG game`,
    description: `Necro's Revenge is a captivating top-down 2D endless hack and slash game, set in a dark and immersive world where players assume the role of Necro, our unique version of the Grim Reaper. Tasked with eliminating all the monsters in his domain, Necro must prove his dominance and restore balance to the underworld. The game combines fast-paced action, strategic combat, and a compelling storyline to create an engaging experience for players of all ages.`,
    category: `game`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Necro's Revenge`,
    format: `Video Game Showcase`,
    date: {
      published: `Still in development`,
      publishedFormat: ``,
    },
    images: {
      feature: NecroImg01,
      annexOne: NecroImg02,
      annexTwo: NecroImg01,
      annexThree: NecroImg04,
      annexFour: NecroImg03,
      annexFive: NecroImg01,
    },
    url: {
      video: `https://www.youtube.com/embed/nE22zZTWzp0?&mute=1`,
      internal: `/games/necros-revenge`,
      external: `/play-necros-revenge`,
    },
  },
  {
    id: 2,
    title: `Solar Apartment Complex`,
    summary: `A 3D architectural visualization rendering of a solar apartment complex.`,
    description: `We produced an architectural visualization rendering of a solar apartment complex. The render highlights the aesthetically pleasing integration of solar panels, contributing to the overall beauty of the design.`,
    category: `3D Render`,
    subcategory: `Architectural Visualization`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `University of Technology, Jamaica`,
    format: `Architectural Visualization`,
    date: {
      published: `April 20, 2023`,
      publishedFormat: `2023-04-20`,
    },
    images: {
      feature: SolarAprtFeatImg,
      annexOne: SolarAprtFeatImg,
      annexTwo: SolarAprtFeatImg,
      annexThree: SolarAprtFeatImg,
      annexFour: SolarAprtFeatImg,
      annexFive: SolarAprtFeatImg,
    },
    url: {
      internal: `/projects/solar-apartment-complex`,
    },
  },
  {
    id: 3,
    title: `Race Car Visualization`,
    summary: `A 3D render of an electric race car highlighting vehicular features and design.`,
    description: `We collaborated with Ontario Tech Racing to spotlight their OTR-20, an electric race car they've been developing. Together, we crafted 3D renders and a trailer to showcase the car's features and design.`,
    category: `3D Render`,
    subcategory: `Digital Advertisement`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Ontario Tech Racing`,
    format: `Digital Advertisement`,
    date: {
      published: `May 21, 2020`,
      publishedFormat: `2020-05-21`,
    },
    images: {
      feature: ElectricRaceCarFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: `https://www.youtube.com/embed/nSk0_Falsac?&mute=1`,
      internal: `/projects/electric-race-car`,
    },
  },
  {
    id: 4,
    title: `The Vault`,
    summary: `A 3D-rendered video trailer.`,
    description: `We crafted a visually stunning 3D-rendered trailer to introduce The Vault, an eagerly anticipated NFT brand. This captivating preview offers a glimpse into the innovative world of digital assets and sets the stage for an unforgettable experience with The Vault.`,
    category: `3D Render`,
    subcategory: `Digital Advertisement`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `The Vault`,
    format: `Video Showcase`,
    date: {
      published: `December 5, 2020`,
      publishedFormat: `2020-12-05`,
    },
    images: {
      feature: TheVaultFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: `https://www.youtube.com/embed/0GLeqEx_X4o?&mute=1`,
      internal: `/projects/the-vault`,
    },
  },
  {
    id: 5,
    title: `Driven`,
    summary: `3D-rendered video advertisement showcasing sneaker design.`,
    description: `The "Driven" shoe brand advertisement showcases a sleek, stylish sneaker, highlighted by a modern 3D rendering that emphasizes its contemporary design and fashion-forward appeal.`,
    category: `Advertisement`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Driven`,
    format: `Digital Advertisement`,
    date: {
      published: `November 14, 2021`,
      publishedFormat: `2021-11-14`,
    },
    images: {
      feature: DrivenAdFeatImg,
      annexOne: DrivenAdImg01,
      annexTwo: DrivenAdImg02,
      annexThree: DrivenAdImg03,
      annexFour: DrivenAdImg04,
      annexFive: DrivenAdFeatImg,
    },
    url: {
      video: `https://www.youtube.com/embed/TGDwVibUtvM?&mute=1`,
      internal: `/projects/driven`,
    },
  },
  {
    id: 6,
    title: `Mountain Dew`,
    summary: `3D-rendered video advertisement showcasing canned soda.`,
    description: `This dynamic 3D-rendered Mountain Dew ad bursts with energy, showcasing the vibrant, exhilarating essence of the drink in a visually captivating and immersive style.`,
    category: `Advertisement`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Mountain Dew`,
    format: `Digital Advertisement`,
    date: {
      published: `January 18, 2022`,
      publishedFormat: `2022-01-18`,
    },
    images: {
      feature: MountainDewAdFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: `https://www.youtube.com/embed/2Z6VqSWiayM?&mute=1`,
      internal: `/projects/mountain-dew`,
    },
  },
  {
    id: 7,
    title: `Office Space`,
    summary: ``,
    description: ``,
    category: `3D Render`,
    subcategory: `Architectural Visualization`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Vittorio Decamron`,
    format: `Architectural Visualization`,
    date: {
      published: `March 17, 2016`,
      publishedFormat: `2016-03-17`,
    },
    images: {
      feature: OfficeSpaceFeatImg,
      annexOne: OfficeSpaceImg01,
      annexTwo: OfficeSpaceImg02,
      annexThree: OfficeSpaceFeatImg,
      annexFour: OfficeSpaceImg01,
      annexFive: OfficeSpaceFeatImg,
    },
    url: {
      internal: `/projects/office-space`,
    },
  },
  {
    id: 8,
    title: `Greenwood Plaza`,
    summary: ``,
    description: ``,
    category: ``,
    subcategory: `Architectural Visualization`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Greenwood Plaza`,
    format: `Architectural Visualization`,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: LogoBackdrop,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
  {
    id: 9,
    title: `AutoCAD Lab`,
    summary: ``,
    description: ``,
    category: `3D Render`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Herbert Morrison Technical High School`,
    format: ``,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: HMTHSAutoCad3dFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: `https://www.youtube.com/embed/8Vr0zOI9mYk?mute=1`,
      internal: `/projects/autocad-lab`,
      external: ``,
    },
  },
  {
    id: 10,
    title: `STEM Lab`,
    summary: ``,
    description: ``,
    category: `3D Render`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Herbert Morrison Technical High School`,
    format: ``,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: HMTHSStemLab3dFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: `https://www.youtube.com/embed/a426Q8mquxM?mute=1`,
      internal: `/projects/stem-lab`,
    },
  },
  {
    id: 11,
    title: `Classroom Visualization`,
    summary: ``,
    description: ``,
    category: `3D Render`,
    subcategory: `Architectural Visualization`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Herbert Morrison Technical High School`,
    format: ``,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: HMTHSClassroom3dFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: `/projects/classroom-visualization`,
    },
  },
  {
    id: 12,
    title: `Campus Virtual Tour`,
    summary: ``,
    description: ``,
    category: `3D Render`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Herbert Morrison Technical High School`,
    format: ``,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: HMTHSCampus3dFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: `/projects/campus-virtual-tour`,
    },
  },
];

export const miscellaneousProjects = [
  {
    id: 1,
    title: `Cookie Quest`,
    summary: ``,
    description: ``,
    category: `game`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Cookie Quest`,
    format: `Game Design`,
    date: {
      published: `March 17, 2016`,
      publishedFormat: `2016-03-17`,
    },
    images: {
      feature: CookieQuestFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
  {
    id: 2,
    title: `Rotten Egg`,
    summary: ``,
    description: ``,
    category: `game`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Rotten Egg`,
    format: `Game Design`,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: ``,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
  {
    id: 3,
    title: `Moondrip`,
    summary: ``,
    description: ``,
    category: `product mockup`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Moondrip`,
    format: ``,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: MoondripFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
  {
    id: 4,
    title: `Fruity Smoothies`,
    summary: ``,
    description: ``,
    category: `product mockup`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Fruity Smoothies`,
    format: ``,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: ``,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
];
