import {
  CookieQuestFeatImg,
  DrivenAdFeatImg,
  DrivenAdImg01,
  DrivenAdImg02,
  DrivenAdImg03,
  DrivenAdImg04,
  ElectricRaceCarFeatImg,
  ElectricRaceCarImg01,
  ElectricRaceCarImg02,
  ElectricRaceCarImg03,
  ElectricRaceCarImg04,
  GwpFeatImg,
  GwpImg01,
  GwpImg02,
  GwpImg03,
  GwpImg04,
  HMTHSAutoCad3dFeatImg,
  HMTHSAutoCad3dImg01,
  HMTHSAutoCad3dImg02,
  HMTHSAutoCad3dImg03,
  HMTHSAutoCad3dImg04,
  HMTHSCampus3dFeatImg,
  HMTHSCampus3dImg01,
  HMTHSCampus3dImg02,
  HMTHSCampus3dImg03,
  HMTHSCampus3dImg04,
  HMTHSClassroom3dFeatImg,
  HMTHSClassroom3dImg01,
  HMTHSClassroom3dImg02,
  HMTHSClassroom3dImg03,
  HMTHSClassroom3dImg04,
  HMTHSStemLab3dFeatImg,
  HMTHSStemLab3dImg01,
  HMTHSStemLab3dImg02,
  HMTHSStemLab3dImg03,
  HMTHSStemLab3dImg04,
  LogoBackdrop,
  MoondripFeatImg,
  MountainDewAdFeatImg,
  MountainDewAdImg01,
  MountainDewAdImg02,
  MountainDewAdImg03,
  MountainDewAdImg04,
  NecroImg01,
  NecroImg02,
  NecroImg03,
  NecroImg04,
  OfficeSpaceFeatImg,
  OfficeSpaceImg01,
  OfficeSpaceImg02,
  SolarAprtFeatImg,
  TheVaultFeatImg,
  TheVaultImg01,
  TheVaultImg02,
  TheVaultImg03,
  TheVaultImg04,
} from "@/assets";

export const projects = [
  {
    id: 1,
    title: `Necro's Revenge`,
    summary: `2D top-down hack-and-slash RPG game`,
    description: `Necro's Revenge is a captivating top-down 2D endless hack and slash game, set in a dark and immersive world where players assume the role of Necro, our unique version of the Grim Reaper. Tasked with eliminating all the monsters in his domain, Necro must prove his dominance and restore balance to the underworld. The game combines fast-paced action, strategic combat, and a compelling storyline to create an engaging experience for players of all ages.`,
    category: `game`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Necro's Revenge`,
    format: `Video Game Showcase`,
    date: {
      published: `Still in development`,
      publishedFormat: ``,
    },
    images: {
      feature: NecroImg01,
      annexOne: NecroImg02,
      annexTwo: NecroImg01,
      annexThree: NecroImg04,
      annexFour: NecroImg03,
      annexFive: NecroImg01,
    },
    url: {
      video: `https://www.youtube.com/embed/nE22zZTWzp0?&mute=1`,
      internal: `/games/necros-revenge`,
      external: `/play-necros-revenge`,
    },
  },
  {
    id: 2,
    title: `Solar Apartment Complex`,
    summary: `A 3D architectural visualization rendering of a solar apartment complex.`,
    description: `We produced an architectural visualization rendering of a solar apartment complex. The render highlights the aesthetically pleasing integration of solar panels, contributing to the overall beauty of the design.`,
    category: `3D Render`,
    subcategory: `Architectural Visualization`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `University of Technology, Jamaica`,
    format: `Architectural Visualization`,
    date: {
      published: `April 20, 2023`,
      publishedFormat: `2023-04-20`,
    },
    images: {
      feature: SolarAprtFeatImg,
      annexOne: SolarAprtFeatImg,
      annexTwo: SolarAprtFeatImg,
      annexThree: SolarAprtFeatImg,
      annexFour: SolarAprtFeatImg,
      annexFive: SolarAprtFeatImg,
    },
    url: {
      internal: `/projects/solar-apartment-complex`,
    },
  },
  {
    id: 3,
    title: `Race Car Visualization`,
    summary: `A 3D render of an electric race car highlighting vehicular features and design.`,
    description: `We collaborated with Ontario Tech Racing to spotlight their OTR-20, an electric race car they've been developing. Together, we crafted 3D renders and a trailer to showcase the car's features and design.`,
    category: `3D Render`,
    subcategory: `Digital Advertisement`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Ontario Tech Racing`,
    format: `Video Showcase`,
    date: {
      published: `May 21, 2020`,
      publishedFormat: `2020-05-21`,
    },
    images: {
      feature: ElectricRaceCarFeatImg,
      annexOne: ElectricRaceCarImg01,
      annexTwo: ElectricRaceCarImg02,
      annexThree: ElectricRaceCarImg03,
      annexFour: ElectricRaceCarImg04,
      annexFive: ElectricRaceCarFeatImg,
    },
    url: {
      video: `https://www.youtube.com/embed/nSk0_Falsac?&mute=1`,
      internal: `/projects/electric-race-car`,
    },
  },
  {
    id: 4,
    title: `The Vault`,
    summary: `A 3D-rendered video trailer.`,
    description: `We crafted a visually stunning 3D-rendered trailer to introduce The Vault, an eagerly anticipated NFT brand. This captivating preview offers a glimpse into the innovative world of digital assets and sets the stage for an unforgettable experience with The Vault.`,
    category: `3D Render`,
    subcategory: `Digital Advertisement`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `The Vault`,
    format: `Video Showcase`,
    date: {
      published: `December 5, 2020`,
      publishedFormat: `2020-12-05`,
    },
    images: {
      feature: TheVaultFeatImg,
      annexOne: TheVaultImg01,
      annexTwo: TheVaultImg02,
      annexThree: TheVaultImg03,
      annexFour: TheVaultImg04,
      annexFive: TheVaultFeatImg,
    },
    url: {
      video: `https://www.youtube.com/embed/0GLeqEx_X4o?&mute=1`,
      internal: `/projects/the-vault`,
    },
  },
  {
    id: 5,
    title: `Driven`,
    summary: `3D-rendered video advertisement showcasing sneaker design.`,
    description: `The "Driven" shoe brand advertisement showcases a sleek, stylish sneaker, highlighted by a modern 3D rendering that emphasizes its contemporary design and fashion-forward appeal.`,
    category: `Advertisement`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Driven`,
    format: `Digital Advertisement`,
    date: {
      published: `November 14, 2021`,
      publishedFormat: `2021-11-14`,
    },
    images: {
      feature: DrivenAdFeatImg,
      annexOne: DrivenAdImg01,
      annexTwo: DrivenAdImg02,
      annexThree: DrivenAdImg03,
      annexFour: DrivenAdImg04,
      annexFive: DrivenAdFeatImg,
    },
    url: {
      video: `https://www.youtube.com/embed/TGDwVibUtvM?&mute=1`,
      internal: `/projects/driven`,
    },
  },
  {
    id: 6,
    title: `Mountain Dew`,
    summary: `3D-rendered video advertisement showcasing canned soda.`,
    description: `This dynamic 3D-rendered Mountain Dew ad bursts with energy, showcasing the vibrant, exhilarating essence of the drink in a visually captivating and immersive style.`,
    category: `Advertisement`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Mountain Dew`,
    format: `Digital Advertisement`,
    date: {
      published: `January 18, 2022`,
      publishedFormat: `2022-01-18`,
    },
    images: {
      feature: MountainDewAdFeatImg,
      annexOne: MountainDewAdImg01,
      annexTwo: MountainDewAdImg02,
      annexThree: MountainDewAdImg03,
      annexFour: MountainDewAdImg04,
      annexFive: MountainDewAdFeatImg,
    },
    url: {
      video: `https://www.youtube.com/embed/2Z6VqSWiayM?&mute=1`,
      internal: `/projects/mountain-dew`,
    },
  },
  {
    id: 7,
    title: `Office Space`,
    summary: `A 3D architectural visualization rendering of an office space.`,
    description: `We produced an architectural visualization rendering of an office space. The render highlights the orderly layout of the necessary equipment, contributing to the overall beauty of the design.`,
    category: `3D Render`,
    subcategory: `Architectural Visualization`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Vittorio Decamron`,
    format: `Architectural Visualization`,
    date: {
      published: `March 17, 2016`,
      publishedFormat: `2016-03-17`,
    },
    images: {
      feature: OfficeSpaceFeatImg,
      annexOne: OfficeSpaceImg01,
      annexTwo: OfficeSpaceImg02,
      annexThree: OfficeSpaceFeatImg,
      annexFour: OfficeSpaceImg01,
      annexFive: OfficeSpaceFeatImg,
    },
    url: {
      internal: `/projects/office-space`,
    },
  },
  // {
  //   id: 8,
  //   title: `Greenwood Plaza`,
  //   summary: `A 3D architectural visualization rendering of a shopping plaza.`,
  //   description: `We produced an architectural visualization rendering of the Greenwood Plaza hardware store. The render highlights the aesthetically pleasing integration of the plaza's brand colors, contributing to the overall beauty of the design.`,
  //   category: `3D Render`,
  //   subcategory: `Architectural Visualization`,
  //   blurb: ``,
  //   details: ``,
  //   endpoint: ``,
  //   client: `Greenwood Plaza`,
  //   format: `Architectural Visualization`,
  //   date: {
  //     published: `November 28, 2024`,
  //     publishedFormat: `2024-11-28`,
  //   },
  //   images: {
  //     feature: GwpFeatImg,
  //     annexOne: GwpImg01,
  //     annexTwo: GwpImg02,
  //     annexThree: GwpImg03,
  //     annexFour: GwpImg04,
  //     annexFive: GwpFeatImg,
  //   },
  //   url: {
  //     video: `https://www.youtube.com/embed/pEtUmi_EaFA?&mute=1`,
  //     internal: `#`,
  //   },
  // },
  {
    id: 9,
    title: `AutoCAD Lab`,
    summary: `A 3D architectural visualization rendering of an AutoCAD Laboratory.`,
    description: `We produced an architectural visualization rendering of an AutoCAD Laboratory for the Herbert Morrison Technical High School. The render highlights the orderly layout of the necessary equipment, contributing to the overall beauty of the design.`,
    category: `3D Render`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Herbert Morrison Technical High School`,
    format: `Architectural Visualization`,
    date: {
      published: `January 16, 2021`,
      publishedFormat: `2021-01-16`,
    },
    images: {
      feature: HMTHSAutoCad3dFeatImg,
      annexOne: HMTHSAutoCad3dImg01,
      annexTwo: HMTHSAutoCad3dImg02,
      annexThree: HMTHSAutoCad3dImg03,
      annexFour: HMTHSAutoCad3dImg04,
      annexFive: HMTHSAutoCad3dFeatImg,
    },
    url: {
      video: `https://www.youtube.com/embed/a426Q8mquxM?mute=1`,
      internal: `/projects/autocad-lab`,
      external: ``,
    },
  },
  {
    id: 10,
    title: `STEM Lab`,
    summary: `A 3D architectural visualization rendering of a STEM Laboratory.`,
    description: `We produced an architectural visualization rendering of a STEM Laboratory for the Herbert Morrison Technical High School. The render highlights the orderly layout of the necessary equipment, contributing to the overall beauty of the design.`,
    category: `3D Render`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Herbert Morrison Technical High School`,
    format: `Architectural Visualization`,
    date: {
      published: `March 8, 2021`,
      publishedFormat: `2021-03-08`,
    },
    images: {
      feature: HMTHSStemLab3dFeatImg,
      annexOne: HMTHSStemLab3dImg01,
      annexTwo: HMTHSStemLab3dImg02,
      annexThree: HMTHSStemLab3dImg03,
      annexFour: HMTHSStemLab3dImg04,
      annexFive: HMTHSStemLab3dFeatImg,
    },
    url: {
      video: `https://www.youtube.com/embed/8Vr0zOI9mYk?mute=1`,
      internal: `/projects/stem-lab`,
    },
  },
  {
    id: 11,
    title: `Classroom Visualization`,
    summary: `A 3D architectural visualization rendering of a classroom in the building of a education institution.`,
    description: `We produced an architectural visualization rendering of a classroom for the Herbert Morrison Technical High School. The render highlights the orderly layout of the necessary equipment, contributing to the overall beauty of the design.`,
    category: `3D Render`,
    subcategory: `Architectural Visualization`,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Herbert Morrison Technical High School`,
    format: `Architectural Visualization`,
    date: {
      published: `February 6, 2019`,
      publishedFormat: `2019-02-06`,
    },
    images: {
      feature: HMTHSClassroom3dFeatImg,
      annexOne: HMTHSClassroom3dImg01,
      annexTwo: HMTHSClassroom3dImg02,
      annexThree: HMTHSClassroom3dImg03,
      annexFour: HMTHSClassroom3dImg04,
      annexFive: HMTHSClassroom3dFeatImg,
    },
    url: {
      video: ``,
      internal: `/projects/classroom-visualization`,
    },
  },
  {
    id: 12,
    title: `Campus Virtual Tour`,
    summary: `A 3D architectural visualization rendering of a campus for a secondary education institution.`,
    description: `We produced an architectural visualization rendering of a campus virtual tour for the Herbert Morrison Technical High School. The render highlights the layout of the various buildings and areas on the campus, contributing to the overall scale of the design.`,
    category: `3D Render`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Herbert Morrison Technical High School`,
    format: `Architectural Visualization`,
    date: {
      published: `January 12, 2019`,
      publishedFormat: `2019-01-12`,
    },
    images: {
      feature: HMTHSCampus3dFeatImg,
      annexOne: HMTHSCampus3dImg01,
      annexTwo: HMTHSCampus3dImg02,
      annexThree: HMTHSCampus3dImg03,
      annexFour: HMTHSCampus3dImg04,
      annexFive: HMTHSCampus3dFeatImg,
    },
    url: {
      video: ``,
      internal: `/projects/campus-virtual-tour`,
    },
  },
];

export const miscellaneousProjects = [
  {
    id: 1,
    title: `Cookie Quest`,
    summary: ``,
    description: ``,
    category: `game`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Cookie Quest`,
    format: `Game Design`,
    date: {
      published: `March 17, 2016`,
      publishedFormat: `2016-03-17`,
    },
    images: {
      feature: CookieQuestFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
  {
    id: 2,
    title: `Rotten Egg`,
    summary: ``,
    description: ``,
    category: `game`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Rotten Egg`,
    format: `Game Design`,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: ``,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
  {
    id: 3,
    title: `Moondrip`,
    summary: ``,
    description: ``,
    category: `product mockup`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Moondrip`,
    format: ``,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: MoondripFeatImg,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
  {
    id: 4,
    title: `Fruity Smoothies`,
    summary: ``,
    description: ``,
    category: `product mockup`,
    subcategory: ``,
    blurb: ``,
    details: ``,
    endpoint: ``,
    client: `Fruity Smoothies`,
    format: ``,
    date: {
      published: ``,
      publishedFormat: ``,
    },
    images: {
      feature: ``,
      annexOne: ``,
      annexTwo: ``,
      annexThree: ``,
      annexFour: ``,
      annexFive: ``,
    },
    url: {
      video: ``,
      internal: ``,
      external: ``,
    },
  },
];
